import streamlit as st
import pandas as pd
import joblib
import os

# ------------------------------------------------------------------
# Page config
# ------------------------------------------------------------------
st.set_page_config(
    page_title="Customer Churn Predictor",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ------------------------------------------------------------------
# Load external CSS
# ------------------------------------------------------------------
def load_css(file_path: str = "style.css") -> None:
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
    else:
        st.warning(f"⚠️ CSS file `{file_path}` not found. Using default styles.")

load_css("style.css")

# ------------------------------------------------------------------
# Load model
# ------------------------------------------------------------------
@st.cache_resource
def load_model():
    return joblib.load("churn_pipeline.pkl")

try:
    model = load_model()
    model_loaded = True
except Exception as e:
    model_loaded = False
    st.error(f"⚠️ Could not load `churn_pipeline.pkl`. Please train the notebook first.\n\n{e}")

# ------------------------------------------------------------------
# Header
# ------------------------------------------------------------------
st.markdown("""
<div class="app-header">
    <h1>📊 Customer Churn Predictor</h1>
    <p>Enter customer details below to estimate the likelihood of churn. Predictions are generated by a machine learning pipeline trained on historical customer data.</p>
</div>
""", unsafe_allow_html=True)

# ------------------------------------------------------------------
# Input form
# ------------------------------------------------------------------
st.markdown('<div class="section-title">Customer Profile</div>', unsafe_allow_html=True)
c1, c2, c3 = st.columns(3)
with c1:
    age = st.number_input("Age", min_value=18, max_value=100, value=35, step=1)
with c2:
    gender = st.selectbox("Gender", ["Male", "Female"])
with c3:
    region = st.selectbox("Region", ["East", "West", "North", "South"])

st.markdown('<div class="section-title">Account & Billing</div>', unsafe_allow_html=True)
c1, c2, c3 = st.columns(3)
with c1:
    tenure_months = st.slider("Tenure (months)", 0, 72, 12)
    monthly_charges = st.number_input("Monthly Charges ($)", min_value=0.0, value=70.0, step=0.5)
with c2:
    total_charges = st.number_input("Total Charges ($)", min_value=0.0, value=2000.0, step=10.0)
    contract_type = st.selectbox("Contract Type", ["Month-to-month", "One year", "Two year"])
with c3:
    payment_method = st.selectbox(
        "Payment Method",
        ["Electronic check", "Mailed check", "Bank transfer", "Credit card"]
    )
    paperless_billing = st.selectbox("Paperless Billing", ["Yes", "No"])

st.markdown('<div class="section-title">Services</div>', unsafe_allow_html=True)
c1, c2, c3 = st.columns(3)
with c1:
    internet_service = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"])
with c2:
    tech_support = st.selectbox("Tech Support", ["Yes", "No", "No internet service"])
with c3:
    online_security = st.selectbox("Online Security", ["Yes", "No", "No internet service"])

st.markdown('<div class="section-title">Usage & Behavior</div>', unsafe_allow_html=True)
c1, c2, c3 = st.columns(3)
with c1:
    num_support_calls = st.number_input("Support Calls", min_value=0, max_value=20, value=1, step=1)
with c2:
    late_payments_last_year = st.number_input("Late Payments (last year)", min_value=0, max_value=20, value=0, step=1)
with c3:
    avg_monthly_usage_gb = st.number_input("Avg Monthly Usage (GB)", min_value=0.0, max_value=1000.0, value=200.0, step=1.0)

# ------------------------------------------------------------------
# Prediction
# ------------------------------------------------------------------
predict_clicked = st.button("Predict Churn", disabled=not model_loaded)

if predict_clicked and model_loaded:
    input_df = pd.DataFrame([{
        "age": age,
        "gender": gender,
        "region": region,
        "tenure_months": tenure_months,
        "monthly_charges": monthly_charges,
        "total_charges": total_charges,
        "contract_type": contract_type,
        "internet_service": internet_service,
        "tech_support": tech_support,
        "online_security": online_security,
        "paperless_billing": paperless_billing,
        "payment_method": payment_method,
        "num_support_calls": num_support_calls,
        "late_payments_last_year": late_payments_last_year,
        "avg_monthly_usage_gb": avg_monthly_usage_gb,
    }])

    try:
        pred = model.predict(input_df)[0]

        # ----- Result card -----
        if str(pred).lower() == "yes":
            st.markdown("""
            <div class="result-card result-churn">
                <div class="result-icon">⚠️</div>
                <div class="result-text">
                    <div class="result-title">Likely to Churn</div>
                    <p class="result-sub">This customer shows a high risk of leaving. Consider a retention offer.</p>
                </div>
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown("""
            <div class="result-card result-stay">
                <div class="result-icon">✅</div>
                <div class="result-text">
                    <div class="result-title">Likely to Stay</div>
                    <p class="result-sub">This customer appears loyal. No immediate action needed.</p>
                </div>
            </div>
            """, unsafe_allow_html=True)

        # ----- Probability card (bonus) -----
        if hasattr(model, "predict_proba"):
            proba = model.predict_proba(input_df)[0]
            classes = list(model.classes_)
            prob_dict = {str(c): float(p) for c, p in zip(classes, proba)}

            p_no  = prob_dict.get("No", 0.0) * 100
            p_yes = prob_dict.get("Yes", 0.0) * 100

            st.markdown(f"""
            <div class="prob-card">
                <div class="prob-title">Prediction Confidence</div>
                <div class="prob-row">
                    <div class="prob-label">Stay</div>
                    <div class="prob-bar-bg">
                        <div class="prob-bar-fill prob-stay" style="width:{p_no:.1f}%;"></div>
                    </div>
                    <div class="prob-val">{p_no:.1f}%</div>
                </div>
                <div class="prob-row">
                    <div class="prob-label">Churn</div>
                    <div class="prob-bar-bg">
                        <div class="prob-bar-fill prob-churn" style="width:{p_yes:.1f}%;"></div>
                    </div>
                    <div class="prob-val">{p_yes:.1f}%</div>
                </div>
            </div>
            """, unsafe_allow_html=True)

            # Insight message
            if p_yes >= 70:
                st.error("High risk — retention action recommended.")
            elif p_yes >= 40:
                st.warning("Moderate risk — monitor this customer closely.")
            else:
                st.success("Low risk — customer is stable.")

    except Exception as e:
        st.error(f"Prediction failed: {e}")

# ------------------------------------------------------------------
# Footer
# ------------------------------------------------------------------
st.markdown("""
<div class="footer">
    Customer Churn Prediction · Built by <b>Zujaja</b> · Scikit-Learn + Streamlit
</div>
""", unsafe_allow_html=True)